//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWA_CORE.Persistent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_Strength_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MST_Strength_Master()
        {
            this.tbl_EMP_Learned_Behaviors = new HashSet<tbl_EMP_Learned_Behaviors>();
            this.tbl_EMP_Realized_Strengths = new HashSet<tbl_EMP_Realized_Strengths>();
            this.tbl_EMP_Unrealized_Strengths = new HashSet<tbl_EMP_Unrealized_Strengths>();
            this.tbl_EMP_Weakness = new HashSet<tbl_EMP_Weakness>();
        }
    
        public int StrengthId { get; set; }
        public string Strength { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public int Encoded_By { get; set; }
        public System.DateTime Encoded_Date { get; set; }
        public Nullable<int> LastChanged_By { get; set; }
        public Nullable<System.DateTime> LastChanged_Date { get; set; }
        public string Computer_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_Learned_Behaviors> tbl_EMP_Learned_Behaviors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_Realized_Strengths> tbl_EMP_Realized_Strengths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_Unrealized_Strengths> tbl_EMP_Unrealized_Strengths { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_Weakness> tbl_EMP_Weakness { get; set; }
    }
}
