//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWA_CORE.Persistent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EMP_DailyCheckIn
    {
        public int DailyCheckInId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> EnergyAtWork_int { get; set; }
        public string EnergyAtWork_value { get; set; }
        public Nullable<int> FocusAtWork_int { get; set; }
        public string FocusAtWork_value { get; set; }
        public Nullable<int> PositiveEmotions_int { get; set; }
        public string PositiveEmotions_value { get; set; }
        public Nullable<int> NegativeEmotions_int { get; set; }
        public string NegativeEmotions_value { get; set; }
        public Nullable<int> Productivity { get; set; }
        public Nullable<double> Prediction { get; set; }
        public bool Active { get; set; }
        public int Encoded_By { get; set; }
        public System.DateTime Encoded_Date { get; set; }
        public Nullable<int> LastChanged_By { get; set; }
        public Nullable<System.DateTime> LastChanged_Date { get; set; }
        public string Computer_Name { get; set; }
        public string Completion { get; set; }
    
        public virtual tbl_MST_Company tbl_MST_Company { get; set; }
        public virtual tbl_REG_Employee_Registration tbl_REG_Employee_Registration { get; set; }
    }
}
