//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWA_CORE.Persistent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MST_Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MST_Company()
        {
            this.tbl_EMP_DailyCheckIn = new HashSet<tbl_EMP_DailyCheckIn>();
            this.tbl_EMP_TISE = new HashSet<tbl_EMP_TISE>();
            this.tbl_MST_Goal_Master = new HashSet<tbl_MST_Goal_Master>();
            this.tbl_MST_Value_Master = new HashSet<tbl_MST_Value_Master>();
            this.tbl_REG_Employee_Registration = new HashSet<tbl_REG_Employee_Registration>();
        }
    
        public int CompanyId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Website { get; set; }
        public string Address { get; set; }
        public string Vision { get; set; }
        public string Mission { get; set; }
        public string Logo { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> IndustryTypeId { get; set; }
        public bool Active { get; set; }
        public int Encoded_By { get; set; }
        public System.DateTime Encoded_Date { get; set; }
        public Nullable<int> LastChanged_By { get; set; }
        public Nullable<System.DateTime> LastChanged_Date { get; set; }
        public string Computer_Name { get; set; }
        public Nullable<System.DateTime> FoundingDate { get; set; }
        public string CompanySize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_DailyCheckIn> tbl_EMP_DailyCheckIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_EMP_TISE> tbl_EMP_TISE { get; set; }
        public virtual tbl_MST_Country_Master tbl_MST_Country_Master { get; set; }
        public virtual tbl_MST_IndustryType_Master tbl_MST_IndustryType_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MST_Goal_Master> tbl_MST_Goal_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MST_Value_Master> tbl_MST_Value_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_REG_Employee_Registration> tbl_REG_Employee_Registration { get; set; }
    }
}
