//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWA_CORE.Persistent.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EMP_DailyCheckIn
    {
        public int DailyCheckInId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> EnergyAtWork { get; set; }
        public Nullable<int> FocusAtWork { get; set; }
        public Nullable<int> PositiveEmotions { get; set; }
        public Nullable<int> NegativeEmotions { get; set; }
        public bool Active { get; set; }
        public int Encoded_By { get; set; }
        public System.DateTime Encoded_Date { get; set; }
        public Nullable<int> LastChanged_By { get; set; }
        public Nullable<System.DateTime> LastChanged_Date { get; set; }
        public string Computer_Name { get; set; }
    
        public virtual tbl_REG_Employee_Registration tbl_REG_Employee_Registration { get; set; }
    }
}
