//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WWA_CORE.Persistent.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WWAEntities : DbContext
    {
        public WWAEntities()
            : base("name=WWAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_CMP_Goals> tbl_CMP_Goals { get; set; }
        public virtual DbSet<tbl_CMP_Values> tbl_CMP_Values { get; set; }
        public virtual DbSet<tbl_EMP_Interest> tbl_EMP_Interest { get; set; }
        public virtual DbSet<tbl_EMP_Learned_Behaviors> tbl_EMP_Learned_Behaviors { get; set; }
        public virtual DbSet<tbl_EMP_Realized_Strengths> tbl_EMP_Realized_Strengths { get; set; }
        public virtual DbSet<tbl_EMP_Unrealized_Strengths> tbl_EMP_Unrealized_Strengths { get; set; }
        public virtual DbSet<tbl_EMP_Weakness> tbl_EMP_Weakness { get; set; }
        public virtual DbSet<tbl_MST_City_Master> tbl_MST_City_Master { get; set; }
        public virtual DbSet<tbl_MST_Company> tbl_MST_Company { get; set; }
        public virtual DbSet<tbl_MST_Country_Master> tbl_MST_Country_Master { get; set; }
        public virtual DbSet<tbl_MST_Gender_Master> tbl_MST_Gender_Master { get; set; }
        public virtual DbSet<tbl_MST_Goal_Master> tbl_MST_Goal_Master { get; set; }
        public virtual DbSet<tbl_MST_IndustryType_Master> tbl_MST_IndustryType_Master { get; set; }
        public virtual DbSet<tbl_MST_Interest_Master> tbl_MST_Interest_Master { get; set; }
        public virtual DbSet<tbl_MST_Strength_Master> tbl_MST_Strength_Master { get; set; }
        public virtual DbSet<tbl_MST_Value_Master> tbl_MST_Value_Master { get; set; }
        public virtual DbSet<tbl_REG_Employee_Registration> tbl_REG_Employee_Registration { get; set; }
    }
}
